test: &default

  # Credentials for REST APIs
  client_id: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: sixneighborrow-facilitator_api1.gmail.com
  password: 5DM8RQ7SP9DUYVLG
  signature: AOH.JxXLRThnyE4tyiz8f.cTKbR2AYOkGZokaguC6yjiLhhLJFa7xoms
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: sixneighborrow-facilitator@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: sandbox
